name: Deployment
on:
  push:
    branches: [ master ]

env:
  CARICAPPS_URL: ${{ secrets.CARICAPPS_URL }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APPS_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          env_file: ".env"
      - run: chmod -R 777 bukti
 
  health:
      needs: deploy
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Check Health
          run: curl --location --request GET '${{secrets.CARICAPPS_URL}}/v1/ping'
  at-api:
      needs: health
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Check Health
          run: curl --location --request GET '${{secrets.CARICAPPS_URL}}/v1/ping'
  at-web:
      needs: health
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Check Health
          run: curl --location --request GET '${{secrets.CARICAPPS_URL}}/v1/ping'
