name: Deployment
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARICAAPPS_URL: ${{ secrets.CARICAAPPS_URL }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APPS_NAME}} #Must be unique in Heroku
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          env_file: ".env"
        # env:
        #   HOST: ${{secrets.CLEARDB_HOST}}
        #   USERNAME: ${{secrets.CLEARDB_USERNAME}}
        #   PASSWORD: ${{secrets.CLEARDB_PASSWORD}}
        #   DATABASE: ${{secrets.CLEARDB_DATABASE}}
 
  health:
      needs: deploy
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Check Health
          run: curl --location --request GET '${{secrets.CARICAAPPS_URL}}/v1/ping'
